default: &default
  adapter: postgresql
  user: <%= ENV["USER"] %>
  password:
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: gshd_development

test:
  <<: *default
  database: gshd_test
