# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 438cd498dba429b4f8a9f2fec2bae33b9c4ca27e73a13e8e59dde57496045bb877e1ff53f6213a8aba3d3f7768fa9a5e8cf300898725c704967ffd807d76a460

test:
  secret_key_base: ea02d2f50d8ec34016a7eb922a78fb5e06860ff5fcc0fc41e25bacf65154b2e3c128b801d6e230947204aa7a48fa4c838d48111394dccc2a20fd24060e4521c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
